M48
; DRILL file KiCad 10.0.3 date 2026-07-12T23:11:42
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-12T23:11:42+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X131.469Y-125.9
X132.0Y-77.8
X182.869Y-92.9
X182.869Y-120.9
M30
